### ISSUE TITLE
License information missing

### ISSUE THREAD

**Issue by mvera-trapeze** [cahnory/jQuery.keyboard#1]
Brilliant plugin, would love to use it in a project, but there is no mention of the license (if any) that this code falls under.

Is this plugin MIT, BSD?

**Comment by cahnory** [comment]
Glay ou like it. The license is MIT so feel free :-). You'll ma fond some useful informations here : http://project.cahnory.fr/project/jquery.keyboard/

**Comment by mvera-trapeze** [comment]
Awesome, thanks!

**Comment by cahnory** [comment]
If it's possible, leave me the url of your project when it'll be done ;-) 

Envoyé depuis mon appareil mobile Samsungmvera-trapeze reply@reply.github.com a écrit :Awesome, thanks!

---
